import './js/header'
import './js/footer'

import './js/game1'
import './js/game2'
import './js/game3'
import './js/game4'
import './js/game5'
import './js/game6'
import './js/game7'
import './js/game8'
import './js/game9'
import './js/slider'